# Generated by Django 4.1.3 on 2022-11-09 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200, null=True)),
                ('Content', models.CharField(max_length=450, null=True)),
                ('CreationDate', models.DateTimeField(auto_now_add=True)),
                ('UpdationDate', models.DateField(null=True)),
                ('signup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enapp.signup')),
            ],
        ),
    ]
